Repository Pda-Final-Project/backend, pull requests merged in 2025-02, with the labels that each got.

#55 P3-60(#53) [MERGE]: 뉴스 조회 API 병합
  data-service/build.gradle
  data-service/settings.gradle
  data-service/src/main/java/finpago/dataservice/news/controller/NewsController.java
  data-service/src/main/java/finpago/dataservice/news/entity/News.java
  data-service/src/main/java/finpago/dataservice/news/service/NewsService.java
  data-service/src/main/resources/application-dev.yml
  data-service/src/main/resources/application.properties
  data-service/src/main/resources/application.yml
Labels: enhancement

#60 [ADD] 관심 종목 추가 구현
  user-service/src/main/java/finpago/userservice/pinnedStock/PinnedStock.java
  user-service/src/main/java/finpago/userservice/pinnedStock/controller/PinnedStockController.java
  user-service/src/main/java/finpago/userservice/pinnedStock/dto/PinnedStockReqDto.java
  user-service/src/main/java/finpago/userservice/pinnedStock/entity/PinnedStock.java
  user-service/src/main/java/finpago/userservice/pinnedStock/repository/PinnedStockRepository.java
  user-service/src/main/java/finpago/userservice/pinnedStock/service/PinnedStockService.java
Labels: Feature

#63 [FIX] 공통 Response code 파일 분리 & 인자 전달방식 수정
  user-service/src/main/java/finpago/userservice/common/global/response/ApiResponse.java
  user-service/src/main/java/finpago/userservice/common/global/response/ResponseCode.java
  user-service/src/main/java/finpago/userservice/pinnedStock/controller/PinnedStockController.java
  user-service/src/main/java/finpago/userservice/pinnedStock/dto/PinnedStockReqDto.java
  user-service/src/main/java/finpago/userservice/pinnedStock/repository/PinnedStockRepository.java
  user-service/src/main/java/finpago/userservice/pinnedStock/service/PinnedStockService.java
Labels: Fix

#62 P3-65 feat/exchange redis
  data-service/build.gradle
  data-service/src/main/java/finpago/dataservice/DataServiceApplication.java
  data-service/src/main/java/finpago/dataservice/exchangeRate/ExchangeRateScheduler.java
  data-service/src/main/java/finpago/dataservice/exchangeRate/ExchangeRateService.java
Labels: Feature

#71 P3 66 feat/pinned stock list
  common/src/main/java/finpago/common/global/exception/error/DuplicatePinnedStockException.java
  user-service/src/main/java/finpago/userservice/common/global/response/ApiResponse.java
  user-service/src/main/java/finpago/userservice/common/global/response/ResponseCode.java
  user-service/src/main/java/finpago/userservice/holdings/entity/Holdings.java
  user-service/src/main/java/finpago/userservice/pinnedStock/controller/PinnedStockController.java
  user-service/src/main/java/finpago/userservice/pinnedStock/dto/PinnedStockResDto.java
  user-service/src/main/java/finpago/userservice/pinnedStock/dto/StockInfo.java
  user-service/src/main/java/finpago/userservice/pinnedStock/repository/PinnedStockRepository.java
  user-service/src/main/java/finpago/userservice/pinnedStock/service/PinnedStockService.java
Labels: Feature, Fix

#73 P3-60 feat/news api
  data-service/build.gradle
  data-service/src/main/java/finpago/dataservice/DataServiceApplication.java
  data-service/src/main/java/finpago/dataservice/news/controller/NewsController.java
  data-service/src/main/resources/application-dev.yml
Labels: Fix
